#!/bin/bash

RELEASE_DIR=/local/bbb/releases

LIBLITMUS_DIR=/local/bbb/liblitmus
LITMUS_DIR=/local/bbb/litmus-rt
FT_TOOLS_DIR=/local/bbb/ft_tools/

BASE_TAG="v4.1.3"

TAG=$1

function die {
    echo $1
    echo
    echo "Usage:      make_release <TAG>"
    echo "Example:    make_release 2007.3"
    echo "Given tag:  '${TAG}'"
    exit 1
}

if [ -z "$TAG"  ]; then
    die "TAG missing."
fi

function archive {
    PREFIX=$1
    TGZ=$2

    TMP=`mktemp`
    git archive --format=tar --prefix=$PREFIX/ $TAG > $TMP || \
	die "Could not create archive from tree."
    gzip -c $TMP > $TGZ || die "Could not compress."
    rm $TMP
}

function release_liblitmus {
    echo "Releasing liblitmus."
    cd $LIBLITMUS_DIR || die "Could not cd to $LIBLITMUS_DIR."
    archive liblitmus $TARGET/liblitmus-$TAG.tgz || die "Could not build archive."
    return 0
}

function release_ft_tools {
    echo "Releasing ft_tools."
    cd $FT_TOOLS_DIR || die "Could not cd to $FT_TOOLS_DIR."
    archive ft_tools $TARGET/ft_tools-$TAG.tgz || die "Could not build archive."
    return 0
}

function release_litmus {
    echo "Releasing LITMUS^RT."
    cd $LITMUS_DIR || die "Could not cd to $LITMUS_DIR."
    git diff -p --stat $BASE_TAG $TAG > $TARGET/litmus-rt-$TAG.patch || \
	die "Could not create patch."
    return 0
}



TARGET="$RELEASE_DIR/$TAG"

mkdir -p $TARGET    || die "Could not make directory $TARGET."


release_litmus      || die "Releasing LITMUS^RT failed."
release_liblitmus   || die "Releasing liblitmus failed."
release_ft_tools    || die "Releasing ft_tools  failed."

cd $TARGET
echo "Generating check sums."
sha256sum * > SHA256SUMS

echo "Release generated in $TARGET."
